version: "3.8"

services:
  rogue_like:
    build: .
    image: rogue-like
    container_name: rogue_like
    command: go run -race main.go
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    environment:
      PORT: 80
    ports:
      - "8080:80"
